###############################################################################
#                          Generated on docker.io                          #
###############################################################################
version: "3.1"
services:

    database:
      image: postgres
      container_name: database
      restart: always
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: admin
        POSTGRES_DB: database
      ports:
        - 5432:5432
      volumes: 
        - ./wall/database/data:/application

    webserver:
      image: nginx:alpine
      container_name: webserver 
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/wall/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    backend:
      build: docker/wall/backend
      container_name: backend
      working_dir: /application
      volumes:
        - ./wall/backend:/application
        - ./docker/wall/backend/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    


